AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65008
      IpAddress: 203.198.186.225
      Type: ipsec.1
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-0f5a6a47f6a25f9f9
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: "password01"
          TunnelInsideCidr: 169.254.40.0/30
        - PreSharedKey: "password01"
          TunnelInsideCidr: 169.254.40.4/30
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-cgw-hkg-01
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-hkg-01
