AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65000
      IpAddress: 49.255.71.2
      Type: ipsec.1
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-0f5a6a47f6a25f9f9
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: u5ieFpS8sR6wjqnHbDMY
          TunnelInsideCidr: 169.254.7.0/30
        - PreSharedKey: u5ieFpS8sR6wjqnHbDMY
          TunnelInsideCidr: 169.254.7.4/30
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-cgw-syd-01
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-syd-01
