AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65006
      IpAddress: 172.110.66.13
      Type: ipsec.1
      Tags:
        -
         Key: Name
         Value: cgw-tor-01
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-067fc30b039641df1
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - TunnelInsideCidr: 169.254.110.72/30
        - TunnelInsideCidr: 169.254.110.76/30
      Tags:
        -
         Key: Name
         Value: vpn-tor-01
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-tor-01connection
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-tor-01
