AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65004
      IpAddress: 4.14.110.226
      Type: ipsec.1
      Tags:
        -
         Key: Name
         Value: cgw-sfo-02
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-067fc30b039641df1
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - TunnelInsideCidr: 169.254.110.56/30
        - TunnelInsideCidr: 169.254.110.60/30
      Tags:
        -
         Key: Name
         Value: vpn-sfo-02
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-sfo-02connection
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-sfo-02
