AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65004
      IpAddress: 4.14.110.226
      Type: ipsec.1
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-0f5a6a47f6a25f9f9
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: !Ref PresharedKey
          TunnelInsideCidr: 169.254.19.0/30
        - PreSharedKey: !Ref PresharedKey
          TunnelInsideCidr: 169.254.19.4/30
  PresharedKey:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Join [ '', ['password used for',cgw-sfo-01-vpn]]
      GenerateSecretString: 
        PasswordLength: 24
        ExcludePunctuation: true
      KmsKeyId: String
      Name: psk-cgw-sfo-01-vpn
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-cgw-sfo-01
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-sfo-01
