AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65000
      IpAddress: 14.202.31.162
      Type: ipsec.1
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-0f5a6a47f6a25f9f9
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: P3vjElqQpUkXNn2Dbf7B
          TunnelInsideCidr: 169.254.8.0/30
        - PreSharedKey: P3vjElqQpUkXNn2Dbf7B
          TunnelInsideCidr: 169.254.8.4/30
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-cgw-syd-02
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-syd-02
