AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65000
      IpAddress: 49.255.71.2
      Type: ipsec.1
      Tags:
        -
         Key: Name
         Value: cgw-syd-01
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-067fc30b039641df1
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - TunnelInsideCidr: 169.254.111.0/30
        - TunnelInsideCidr: 169.254.111.4/30
      Tags:
        -
         Key: Name
         Value: vpn-syd-01
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-syd-01connection
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-syd-01
