AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65006
      IpAddress: 172.110.66.2
      Type: ipsec.1
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-0f5a6a47f6a25f9f9
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: testpassword000001x
          TunnelInsideCidr: 169.254.12.0/30
        - PreSharedKey: testpassword000001x
          TunnelInsideCidr: 169.254.12.4/30
  PresharedKey:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: String
      GenerateSecretString: 
        GenerateSecretString
      KmsKeyId: String
      Name: presharekey-regex
      Tags: 
        - Tag

Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-cgw-tor-01
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-tor-01
