AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: 65000
      IpAddress: 119.225.143.98
      Type: ipsec.1
      Tags:
        -
         Key: Name
         Value: cgw-syd-02
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: tgw-067fc30b039641df1
      Type: ipsec.1
      VpnTunnelOptionsSpecifications: 
        - TunnelInsideCidr: 169.254.111.8/30
        - TunnelInsideCidr: 169.254.111.12/30
      Tags:
        -
         Key: Name
         Value: vpn-syd-02
Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: vpn-syd-02connection
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: cgw-syd-02
