AWSTemplateFormatVersion: "2010-09-09"

Description: Customer Gateway for Transit Gateway

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties: 
      BgpAsn: regexbgpasn
      IpAddress: regexendpoint
      Type: regexvpntype
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref CustomerGateway
      StaticRoutesOnly: False
      TransitGatewayId: regextgwid
      Type: regexvpntype
      VpnTunnelOptionsSpecifications: 
        - PreSharedKey: !Ref PreSharedKey
          TunnelInsideCidr: regextunnelinside01
        - PreSharedKey: !Ref PreSharedKey
          TunnelInsideCidr: regextunnelinside02
  PresharedKey:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Join
        - 'password used for'
        - !Ref VPNConnection
      GenerateSecretString: 
        GenerateSecretString:
        PasswordLength: 24

      KmsKeyId: String
      Name: psk-regexcgw


Outputs:
  VPNConnection:
    Description: A reference to the created VPN Connection
    Value: !Ref VPNConnection
    Export:
      Name: regexvpnconnection
  CustomerGateway:
    Description: A reference to the created Customer Gateway
    Value: !Ref CustomerGateway
    Export:
      Name: regexcgw